name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        check-latest: true

    - name: Clone Repo
      run: |
        git clone https://github.com/aurora-develop/aurora

    - name: Build binary
      run: |
        cd aurora
        mkdir -p artifact
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o aurora -a -ldflags '-s -w -extldflags "-static"' . && rm -f artifact/aurora && cp aurora artifact/aurora && cd artifact && tar -czvf ../aurora-linux-amd64.tar.gz * && cd ..
        GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o aurora -a -ldflags '-s -w -extldflags "-static"' . && rm -f artifact/aurora && cp aurora artifact/aurora && cd artifact && tar -czvf ../aurora-windows-amd64.tar.gz * && cd ..
        GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o aurora -a -ldflags '-s -w -extldflags "-static"' . && rm -f artifact/aurora && cp aurora artifact/aurora && cd artifact && tar -czvf ../aurora-darwin-amd64.tar.gz * && cd ..
        GOOS=freebsd GOARCH=amd64 CGO_ENABLED=0 go build -o aurora -a -ldflags '-s -w -extldflags "-static"' . && rm -f artifact/aurora && cp aurora artifact/aurora && cd artifact && tar -czvf ../aurora-freebsd-amd64.tar.gz * && cd ..
        cd ..
        
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: aurora-pre-built.zip
        path: |
            aurora/aurora-linux-amd64.tar.gz
            aurora/aurora-windows-amd64.tar.gz
            aurora/aurora-darwin-amd64.tar.gz
            aurora/aurora-freebsd-amd64.tar.gz
            
    - name: Get latest version
      run: |
        version=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "VERSION=$version" >> $GITHUB_ENV
        
    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        files: |
            aurora/aurora-linux-amd64.tar.gz
            aurora/aurora-windows-amd64.tar.gz
            aurora/aurora-darwin-amd64.tar.gz
            aurora/aurora-freebsd-amd64.tar.gz
              
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 8
