name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
        
    - name: Run tests
      run: go test -v ./...
        
    - name: Cross compile
      run: |
        go get
        export CGO_ENABLED=0
        PKG=aurora
        targets=(
            "windows/amd64"
            "linux/amd64"
            "darwin/amd64"
            "windows/386"
            "linux/386"
            "linux/arm"
            "linux/arm64"
        )
        upxPath=$(command -v upx)
        for target in "${targets[@]}"; do
            GOOS=${target%/*}
            GOARCH=${target#*/}
            output="bin/${GOOS}_${GOARCH}/${PKG}"
            mkdir -p $(dirname ${output})
            GOOS=$GOOS GOARCH=$GOARCH go build -ldflags="-s -w -extldflags '-static'" -o ${output} *.go
            if [ -n "$upxPath" ]; then
                $upxPath -9 ${output}
            fi
        done
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: aurora
        path: bin
    - name: Set up permissions
      run: |
          git config --global url."https://${{ secrets.GHCR_PAT }}:@github.com/".insteadOf "https://github.com/"
      env:
    GHCR_PAT: ${{ secrets.GHCR_PAT }}        
        - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/*"
        token: ${{ secrets.GHCR_PAT }}
        generateReleaseNotes: true
