name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create tag
        run: git tag v2.2.2

      - name: Push tag
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        run: git push origin v2.2.2

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        with:
          tag_name: v2.2.2
          name: Release v2.2.2
          files: |
            aurora-linux-amd64.tar.gz
            aurora-linux-arm64.tar.gz
            aurora-windows-amd64.tar.gz
            aurora-darwin-amd64.tar.gz
            aurora-freebsd-amd64.tar.gz
